[package]
name = "emulation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
delay_map = "0.1.1"

# TODO: Switch back from the forked one, once libp2p-gossipsub supports protobuf encoding.
#libp2p = { version = "0.46.1", default-features = false, features = ["gossipsub", "dns-tokio", "tcp-tokio", "noise", "mplex", "yamux", "serde"] }
libp2p = { git = "https://github.com/ackintosh/rust-libp2p.git", rev = "4db881d95f9bd661d274b734c814ef766a84c400", default-features = false, features = ["gossipsub", "dns-tokio", "tcp-tokio", "noise", "mplex", "yamux", "serde"] }

# This is a fork of `libp2p` in order to emulate malicious behaviour.
# This `libp2p-testground` is used in `attacker` module instead of `libp2p`.
# See https://github.com/ackintosh/rust-libp2p/pull/45
libp2p-testground = { git = "https://github.com/ackintosh/rust-libp2p.git", branch = "gossipsub-testground", package = "libp2p", default-features = false, features = ["gossipsub", "dns-tokio", "tcp-tokio", "noise", "mplex", "yamux", "serde"] }

rand = "0.8.5"
serde = "1.0.139"
serde_json = "1.0.82"
# TODO: Update once the version next (v0.3.1) has been released.
testground = { git = "https://github.com/testground/sdk-rust.git", rev = "d6af289b7ce0d58185b4918f424c7f2aacdd4200" }
tokio = { version = "1.20.0", features = ["macros"] }
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.14", features = ["env-filter"] }

# TODO: Switch back from the forked one, once the PR is merged.
# https://github.com/prometheus/client_rust/pull/47
prometheus-client = { git = "https://github.com/ackintosh/client_rust.git", rev = "2c16ebc31cb8b2d36a6fb7d49308f87f11ff2558", features = ["protobuf"] }

prost = "0.10"

[patch]
[patch.crates-io]
# TODO 1: Switch back from the forked one, once the PR is merged.
# https://github.com/prometheus/client_rust/pull/47
# TODO 2: Remove this once libp2p-gossipsub supports protobuf encoding.
prometheus-client = { git = "https://github.com/ackintosh/client_rust.git", rev = "2c16ebc31cb8b2d36a6fb7d49308f87f11ff2558"}
